var RwLanguages = {};
RwLanguages.cultures = {};
if (!localStorage.getItem('currentCulture')) {
    localStorage.setItem('currentCulture', 'enUs');
}
RwLanguages.currentCulture = localStorage.getItem('currentCulture');

RwLanguages.translate = function(caption) {
    var translatedCaption = this.cultures[this.currentCulture][caption];
    if (typeof translatedCaption === 'string') {
        return translatedCaption;
    } else {
        return caption;
    }
};

RwLanguages.captions = [
    '.NET Union'
  , '0 items found'
  , 'About'
  , 'Accident'
  , 'Account'
  , 'Action'
  , 'Add Complete'
  , 'Add Item'
  , 'Add'
  , 'Address'
  , 'Add/Replace'
  , 'Admin Password'
  , 'Aisle'
  , 'All'
  , 'All Statuses'
  , 'Amber'
  , 'Application'
  , 'Application Settings'
  , 'Apply All Qty Items'
  , 'Approve'
  , 'Approve Charge'
  , 'Approve Charges'
  , 'Approve Invoiced'
  , 'Approve Period'
  , 'Approved'
  , 'As Of'
  , 'Assign Bar Code(s)'
  , 'Attach'
  , 'Attribute'
  , 'Audit'
  , 'Available Driver'
  , 'Available Vehicle'
  , 'Back'
  , 'Background Image'
  , 'Bar Code'
  , 'Bar Code(s)'
  , 'Bar Code / I-Code'
  , 'Bar Code No'
  , 'BC'
  , 'Billing Reports'
  , 'Black'
  , 'Blue'
  , 'Bokeh'
  , 'Browse'
  , 'Browse View'
  , 'Brushed Metal'
  , 'Calculate'
  , 'Calendar'
  , 'Cancel'
  , 'Cancel Quote'
  , 'Cancel Request'
  , 'Catalog'
  , 'Category'
  , 'Certification'
  , 'Charge'
  , 'Charge Processing'
  , 'Charges'
  , 'Check-In'
  , 'Check-In (Deal)'
  , 'Check-In (Multi Order)'
  , 'Check-In (Single Order)'
  , 'Check-In (Session)'
  , 'Check In Item'
  , 'Check-In Menu'
  , 'Check-Out'
  , 'Circles'
  , 'Classification'
  , 'Clear'
  , 'Clear Signature'
  , 'Clear Status'
  , 'Claim'
  , 'Close'
  , 'Close Order'
  , 'Close Project'
  , 'Close Rental Agreement'
  , 'Closed'
  , 'Complete'
  , 'Complete Order'
  , 'Complete QC'
  , 'Condition'
  , 'Connections'
  , 'Contact'
  , 'Contact Settings'
  , 'Contact Event'
  , 'Contact Title'
  , 'Continue?'
  , 'Continue...'
  , 'Control'
  , 'Cost'
  , 'Cost Category'
  , 'Count'
  , 'Credit'
  , 'Credit Status'
  , 'Create Contract'
  , 'Create Contract Transaction'
  , 'Customer'
  , 'Customer Revenue'
  , 'Customer Revenue Summary'
  , 'Customer Settings'
  , 'Customer Category'
  , 'Customer Type'
  , 'Daily Drivers Rate Card'
  , 'Daily Revenue'
  , 'Dark Grey'
  , 'Default'
  , 'Deactivate'
  , 'Deal'
  , 'Deal Desc.'
  , 'Deal No'
  , 'Deal No.'
  , 'Deal Reports'
  , 'Delete'
  , 'Department'
  , 'Department:'
  , 'Department Settings'
  , 'Desc'
  , 'Description'
  , 'Detail'
  , 'Document'
  , 'Document Type'
  , 'DOT'
  , 'Driver'
  , 'Driver Classification'
  , 'Driver Control'
  , 'Driver CSATF Log'
  , 'Driver Document'
  , 'Driver Duty Hours'
  , 'Driver Duty Hours/Violation'
  , 'Driver Employee No'
  , 'Driver Group'
  , 'Driver History'
  , 'Driver License'
  , 'Driver Pull Notice'
  , 'Driver Pull Notice Format 2'
  , 'Driver Reports'
  , 'Driver Restriction'
  , 'Driver Settings'
  , 'Driver Status'
  , 'Driver Suffix'
  , 'Driver Settings'
  , 'Driver Union'
  , 'Driver Violation'
  , 'Drivers'
  , 'Edit'
  , 'Edit Charges'
  , 'Edit PO'
  , 'E-mail'
  , 'E-mail / Username'
  , 'E-mail Server'
  , 'E-mail is required'
  , 'End Date'
  , 'End of Day Process'
  , 'Endorsement'
  , 'Episode'
  , 'Equipment'
  , 'Equipment Charge Export'
  , 'Equipment Batch Revenue'
  , 'Error'
  , 'Estimated Start Date'
  , 'Estimated End Date'
  , 'Event'
  , 'Executive Settings'
  , 'Exchange'
  , 'Export'
  , 'Export To Excel'
  , 'First scan must be a Bar Code...'
  , 'Flower'
  , 'For'
  , 'From Truck'
  , 'From Warehouse'
  , 'Fuel'
  , 'Fuel Type'
  , 'General'
  , 'Grand Total'
  , 'Grass'
  , 'Green'
  , 'Group'
  , 'Groups'
  , 'Help'
  , 'History'
  , 'Hold'
  , 'Hold Vehicle'
  , 'Home'
  , 'Hotfixes'
  , 'How many?'
  , 'I-Code'
  , 'Image'
  , 'In'
  , 'In Repair'
  , 'Inventory'
  , 'Inventory No.'
  , 'Inventory Web Image'
  , 'Invoice'
  , 'Invoice Paid'
  , 'Invoice Report'
  , 'IRA'
  , 'Item Status'
  , 'Items'
  , 'Last Deal'
  , 'Last Deal No'
  , 'Last Order'
  , 'Last Order No'
  , 'License Class'
  , 'Light Blue'
  , 'Liquid'
  , 'List'
  , 'Location'
  , 'Location Status'
  , 'Location Unit'
  , 'Login'
  , 'Logoff'
  , 'Mail List'
  , 'Maintenance'
  , 'Message'
  , 'Messages'
  , 'Miscellaneous'
  , 'Miscellaneous Charge Export'
  , 'Miscellaneous Charges'
  , 'Miscellaneous Processing'
  , 'Miscellaneous Settings'
  , 'Mode'
  , 'Move To Location'
  , 'Multi-Order'
  , 'New'
  , 'New Order'
  , 'Next'
  , 'None'
  , 'Note'
  , 'Notes'
  , 'No'
  , 'OK'
  , 'On PO'
  , 'Open'
  , 'Open Rental Agreement'
  , 'Open Ticket'
  , 'Options'
  , 'Out'
  , 'Ord'
  , 'Order'
  , 'Ordered'
  , 'Order Desc.'
  , 'Order No'
  , 'Order Number'
  , 'Order Type'
  , 'Ordered'
  , 'Origin Cost'
  , 'Other'
  , 'Overlay Color'
  , 'Package Truck'
  , 'Package Truck Menu'
  , 'Paid Period'
  , 'Paper'
  , 'Pass'
  , 'Password'
  , 'Password is required'
  , 'Pending'
  , 'Performance Note'
  , 'Period Total'
  , 'Photo'
  , 'Physical Inventory'
  , 'Physical Inventory No'
  , 'Photo Description'
  , 'Picture'
  , 'Pictures'
  , 'PO'
  , 'PO Desc.'
  , 'PO No'
  , 'PO No.'
  , 'PO Receive'
  , 'PO Return'
  , 'Pop Out'
  , 'Post Status'
  , 'Preferences'
  , 'Previous Quotes'
  , 'Print'
  , 'Privacy Policy'
  , 'Process'
  , 'Process Ticket'
  , 'Production'
  , 'Production Type'
  , 'Production Upload'
  , 'Profile'
  , 'Project'
  , 'Project Charges'
  , 'Project Header'
  , 'Project Revenue'
  , 'Project Settings'
  , 'Project Status'
  , 'Project Type'
  , 'Prospect'
  , 'Purchase Order'
  , 'QC'
  , 'QC Rq\'d'
  , 'Quik Check-In'
  , 'Qty'
  , 'QuikPick'
  , 'Quote'
  , 'Quote No'
  , 'Quote / Order No'
  , 'Rate'
  , 'Rate Table'
  , 'Rate Card Drivers'
  , 'Rate Card Project'
  , 'Recalculate'
  , 'Receive'
  , 'Receive by'
  , 'Receive Inventory'
  , 'Recover Password'
  , 'Red'
  , 'Reef'
  , 'Remit To'
  , 'Repair Settings'
  , 'Return Inventory'
  , 'Receive PO'
  , 'Received'
  , 'Refresh'
  , 'Release'
  , 'Released'
  , 'Remain'
  , 'Remaining'
  , 'Remove Item'
  , 'Rental'
  , 'Rental Agreement'
  , 'Rental Agreement Accruals'
  , 'Rental Agreement Batch Revenue'
  , 'Rental Agreement Charge Export'
  , 'Rental Agreement Contract'
  , 'Rental Agreement Invoice Log'
  , 'Rental Agreement Processing'
  , 'Rental Agreement Reports'
  , 'Rental Agreement Settings'
  , 'RentalWorks'
  , 'Reopen'
  , 'Re-open Charged Ticket'
  , 'Repair'
  , 'Repair (Complete)'
  , 'Repair (Release)'
  , 'Repair Menu'
  , 'Repair No. / BC'
  , 'Repair Order'
  , 'Repair Order Listing'
  , 'Repair Order Settings'
  , 'Repair Order Charge Export'
  , 'Replace'
  , 'Reports'
  , 'Requirements'
  , 'Return'
  , 'Return by'
  , 'Returned'
  , 'Responsible Person'
  , 'Restriction'
  , 'Revenue'
  , 'Revise'
  , 'Rmn'
  , 'Rusted Metal'
  , 'SAP Settings'
  , 'SAP'
  , 'Save'
  , 'Scan'
  , 'Scan Barcode'
  , 'Scan Mode'
  , 'Schedule'
  , 'Schedule Header'
  , 'Schedule Message'
  , 'Schedule Settings'
  , 'Security'
  , 'Select Deal...'
  , 'Select Item to Check-In...'
  , 'Select Item to Stage...'
  , 'Select Order...'
  , 'Select PO...'
  , 'Select Package Truck'
  , 'Select Physical Inventory'
  , 'Select PO (Receive)'
  , 'Select PO (Return)'
  , 'Select Deal'
  , 'Select Order'
  , 'Select PO'
  , 'Select Session'
  , 'Select Transfer'
  , 'Serial No. Selection'
  , 'Select QuikPick Type'
  , 'Service'
  , 'Service Order'
  , 'Service Settings'
  , 'Session'
  , 'Session No'
  , 'Session In'
  , 'Settings'
  , 'Shelf'
  , 'Show Active'
  , 'Show All'
  , 'Show Inactive'
  , 'Signature'
  , 'Sign In'
  , 'Silver'
  , 'Single Order'
  , 'Stage'
  , 'Staging'
  , 'Staged'
  , 'Staged/Out'
  , 'Start Date'
  , 'Status'
  , 'Sub'
  , 'Sub By'
  , 'Sub-Receive'
  , 'Sub-Rental'
  , 'Sub-Rental/Sale'
  , 'Sub-Return'
  , 'Sub-Sale'
  , 'Submit'
  , 'Suffix'
  , 'Support'
  , 'Summary'
  , 'Support'
  , 'Source'
  , 'Swap'
  , 'Take Picture'
  , 'Text Color'
  , 'Texture'
  , 'Ticket'
  , 'Ticket Charges'
  , 'Ticket Message'
  , 'Ticket Report'
  , 'Tint'
  , 'Title'
  , 'Toggle Call Given'
  , 'Toggle Invoiced'
  , 'Toggle Non-Working'
  , 'Toggle Paid'
  , 'To Truck'
  , 'To Warehouse'
  , 'Total'
  , 'Tracked By'
  , 'Transfer'
  , 'Transfer In Menu'
  , 'Transfer Order'
  , 'Transparent'
  , 'TransWorks'
  , 'TransWorks.NET'
  , 'Trip Ticket Driver Time Card'
  , 'Trip Ticket Category'
  , 'Truck'
  , 'Truck No.'
  , 'Type'
  , 'Update'
  , 'User'
  , 'Unapprove'
  , 'Unapprove Charge'
  , 'Unapprove Charges'
  , 'Union'
  , 'Unit'
  , 'Unstage'
  , 'Unstage Item?'
  , 'Update'
  , 'Update Charge No'
  , 'Update Hiatus'
  , 'Update Ticket Charge No'
  , 'Update WA'
  , 'Utilities'
  , 'Vehicle'
  , 'Vehicle Attribute'
  , 'Vehicle Accrued Rental Expense'
  , 'Vehicle Catalog'
  , 'Vehicle Cost Summary'
  , 'Vehicle Cost Detail'
  , 'Vehicle Daily Out Of Service'
  , 'Vehicle Document'
  , 'Vehicle Endorsement'
  , 'Vehicle History'
  , 'Vehicle Location'
  , 'Vehicle Repair Cost'
  , 'Vehicle Reports'
  , 'Vehicle Revenue/Usage Analysis'
  , 'Vehicle Service'
  , 'Vehicle Settings'
  , 'Vehicle Status'
  , 'Vehicle Type'
  , 'Vendor'
  , 'Vendor/Consignor'
  , 'Vendor Classification'
  , 'Vendor Reports'
  , 'Vendor Settings'
  , 'Violation'
  , 'Void'
  , 'Warehouse'
  , 'Waterfall'
  , 'Web Image'
  , 'White'
  , 'Would you like to add this to the order?'
  , 'Yes'
  , 'Yosemite'
];

RwLanguages.cultures.neutral = {};
(function() {
    for (var i = 0; i < RwLanguages.captions.length; i++) {
        RwLanguages.cultures.neutral[RwLanguages.captions[i]] = RwLanguages.captions[i];
    }
})();

RwLanguages.cultures.en = {

};

RwLanguages.cultures.enUs = {

};

RwLanguages.cultures.es = {
    'Barcode / Icode': 'Código Barras / I-Code'
  , 'Check-In': 'Facturar'
  , 'Check-In Menu': 'Facturar Menú'
  , 'Deal': 'Tratar'
  , 'Home': 'Casa'
  , 'Email': 'E-mail'
  , 'Exchange': 'Intercambio'
  , 'Inventory': 'Inventario'
  , 'Item Status': 'Estado Elemento'
  , 'Login': 'Iniciar Sesión'
  , 'Logoff': 'Cierre Sesión'
  , 'Multi-Order': 'Multi-Order'
  , 'Options': 'Opciones'
  , 'Order': 'Orden'
  , 'Package Truck': 'Paquete Camiones'
  , 'Physical Inventory': 'Physical Inventory'
  , 'Password': 'Password'
  , 'QC': 'QC'
  , 'Scan Barcode': 'Scan Barcode'
  , 'Repair': 'Repair'
  , 'Single Order': 'Single Order'
  , 'Session': 'Session'
  , 'Staging': 'Staging'
  , 'Sub-Receive': 'Sub-Receive'
  , 'Sub-Return': 'Sub-Return'
  , 'Transfer': 'Transfer'
  , 'Utilities': 'Utilities'
};

RwLanguages.cultures.en   = jQuery.extend({}, RwLanguages.cultures.neutral, RwLanguages.cultures.en);
RwLanguages.cultures.enUs = jQuery.extend({}, RwLanguages.cultures.en,      RwLanguages.cultures.enUs);
RwLanguages.cultures.es   = jQuery.extend({}, RwLanguages.cultures.neutral, RwLanguages.cultures.es);
