//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitekPaymentCaptureService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", ConfigurationName="VisitekPaymentCaptureService.PaymentCapture_Port")]
    public interface PaymentCapture_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture:ProcessCardPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<VisitekPaymentCaptureService.ProcessCardPayment_Result> ProcessCardPaymentAsync(VisitekPaymentCaptureService.ProcessCardPayment request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture:GetApiKey", ReplyAction="*")]
        System.Threading.Tasks.Task<VisitekPaymentCaptureService.GetApiKey_Result> GetApiKeyAsync(VisitekPaymentCaptureService.GetApiKey request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessCardPayment", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", IsWrapped=true)]
    public partial class ProcessCardPayment
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", Order=0)]
        public string pINPadNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", Order=1)]
        public int transactionTypeOpt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", Order=2)]
        public string amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", Order=3)]
        public string docRefNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", Order=4)]
        public string storeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", Order=5)]
        public string salespersonCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", Order=6)]
        public string billToCustomerNo;
        
        public ProcessCardPayment()
        {
        }
        
        public ProcessCardPayment(string pINPadNo, int transactionTypeOpt, string amount, string docRefNo, string storeCode, string salespersonCode, string billToCustomerNo)
        {
            this.pINPadNo = pINPadNo;
            this.transactionTypeOpt = transactionTypeOpt;
            this.amount = amount;
            this.docRefNo = docRefNo;
            this.storeCode = storeCode;
            this.salespersonCode = salespersonCode;
            this.billToCustomerNo = billToCustomerNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessCardPayment_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", IsWrapped=true)]
    public partial class ProcessCardPayment_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", Order=0)]
        public string return_value;
        
        public ProcessCardPayment_Result()
        {
        }
        
        public ProcessCardPayment_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApiKey", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", IsWrapped=true)]
    public partial class GetApiKey
    {
        
        public GetApiKey()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApiKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", IsWrapped=true)]
    public partial class GetApiKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PaymentCapture", Order=0)]
        public string return_value;
        
        public GetApiKey_Result()
        {
        }
        
        public GetApiKey_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PaymentCapture_PortChannel : VisitekPaymentCaptureService.PaymentCapture_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PaymentCapture_PortClient : System.ServiceModel.ClientBase<VisitekPaymentCaptureService.PaymentCapture_Port>, VisitekPaymentCaptureService.PaymentCapture_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PaymentCapture_PortClient() : 
                base(PaymentCapture_PortClient.GetDefaultBinding(), PaymentCapture_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PaymentCapture_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentCapture_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(PaymentCapture_PortClient.GetBindingForEndpoint(endpointConfiguration), PaymentCapture_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentCapture_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PaymentCapture_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentCapture_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PaymentCapture_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentCapture_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisitekPaymentCaptureService.ProcessCardPayment_Result> VisitekPaymentCaptureService.PaymentCapture_Port.ProcessCardPaymentAsync(VisitekPaymentCaptureService.ProcessCardPayment request)
        {
            return base.Channel.ProcessCardPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisitekPaymentCaptureService.ProcessCardPayment_Result> ProcessCardPaymentAsync(string pINPadNo, int transactionTypeOpt, string amount, string docRefNo, string storeCode, string salespersonCode, string billToCustomerNo)
        {
            VisitekPaymentCaptureService.ProcessCardPayment inValue = new VisitekPaymentCaptureService.ProcessCardPayment();
            inValue.pINPadNo = pINPadNo;
            inValue.transactionTypeOpt = transactionTypeOpt;
            inValue.amount = amount;
            inValue.docRefNo = docRefNo;
            inValue.storeCode = storeCode;
            inValue.salespersonCode = salespersonCode;
            inValue.billToCustomerNo = billToCustomerNo;
            return ((VisitekPaymentCaptureService.PaymentCapture_Port)(this)).ProcessCardPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VisitekPaymentCaptureService.GetApiKey_Result> VisitekPaymentCaptureService.PaymentCapture_Port.GetApiKeyAsync(VisitekPaymentCaptureService.GetApiKey request)
        {
            return base.Channel.GetApiKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<VisitekPaymentCaptureService.GetApiKey_Result> GetApiKeyAsync()
        {
            VisitekPaymentCaptureService.GetApiKey inValue = new VisitekPaymentCaptureService.GetApiKey();
            return ((VisitekPaymentCaptureService.PaymentCapture_Port)(this)).GetApiKeyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PaymentCapture_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PaymentCapture_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.8.103:8047/TEST_NAV80/WS/Vistek Live/Codeunit/PaymentCapture");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PaymentCapture_PortClient.GetBindingForEndpoint(EndpointConfiguration.PaymentCapture_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PaymentCapture_PortClient.GetEndpointAddress(EndpointConfiguration.PaymentCapture_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            PaymentCapture_Port,
        }
    }
}
