var RwLanguages = {};
RwLanguages.cultures = {};

RwLanguages.currentCulture = localStorage.getItem('currentCulture');

RwLanguages.translate = function(caption) {
    var translatedCaption = this.cultures[this.currentCulture][caption];
    if (typeof translatedCaption === 'string') {
        return translatedCaption;
    } else {
        return caption;
    }
};

RwLanguages.captions = [
    '0 items found'
  , 'Account'
  , 'Add Complete'
  , 'Add Container to Order'
  , 'Add Item'
  , 'Add'
  , 'Add/Replace'
  , 'Add All Qty Items'
  , 'Admin Password'
  , 'Aisle'
  , 'All'
  , 'Amber'
  , 'Apply All Qty Items'
  , 'Are you finished filling this Container?'
  , 'As Of'
  , 'Assign Bar Code(s)'
  , 'Assign Items'
  , 'Asset Disposition'
  , 'Item Location'
  , 'Item Set Location'
  , 'Attach'
  , 'Available For'
  , 'Back'
  , 'Background Image'
  , 'Barcode'
  , 'Bar Code'
  , 'Bar Code(s)'
  , 'Bar Code / I-Code'
  , 'Barcode / I-Code'
  , 'BC / Serial'
  , 'Bar Code No'
  , 'Barcode Image'
  , 'Barcode Label'
  , 'BC'
  , 'Black'
  , 'Blue'
  , 'Bokeh'
  , 'Brushed Metal'
  , 'Buyer'
  , 'Cancel'
  , 'Cancel Quote'
  , 'Cancel Request'
  , 'Check-In'
  , 'Check-In (Deal)'
  , 'Check-In (Multi Order)'
  , 'Check-In (Single Order)'
  , 'Check-In (Session)'
  , 'Check-In Date'
  , 'Check In Item'
  , 'Check-In Menu'
  , 'Check-Out'
  , 'Circles'
  , 'Clear'
  , 'Clear Signature'
  , 'Close'
  , 'Close Container'
  , 'Complete'
  , 'Complete QC'
  , 'Condition'
  , 'Confirm'
  , 'Consignor'
  , 'Container'
  , 'Container<br/>Item'
  , 'Container<br/>Desc'
  , 'Container Items'
  , 'Container No'
  , 'Container<br/>No'
  , 'Continue?'
  , 'Continue...'
  , 'Continue'
  , 'Count'
  , 'Count Type'
  , 'Create Container'
  , 'Create Contract'
  , 'Create New Set'
  , 'CUSTOM'
  , 'Customer'
  , 'Damage'
  , 'Dark Grey'
  , 'Date'
  , 'Deal'
  , 'Deal Desc.'
  , 'Deal No'
  , 'Deal No.'
  , 'Deal / Vendor'
  , 'Department'
  , 'Department:'
  , 'Dept Code'
  , 'Desc'
  , 'Description'
  , 'Direction'
  , 'Edit'
  , 'E-mail'
  , 'E-mail is required'
  , 'End Date'
  , 'Error'
  , 'Est'
  , 'Est Dates'
  , 'Estimated Start Date'
  , 'Estimated End Date'
  , 'Event No'
  , 'Exchange'
  , 'Fill Container'
  , 'First scan must be a Bar Code...'
  , 'Flower'
  , 'For'
  , 'From Truck'
  , 'From Warehouse'
  , 'Grand Total'
  , 'Grass'
  , 'Green'
  , 'Home'
  , 'How many?'
  , 'I-Code'
  , 'In'
  , 'In Repair'
  , 'In Warehouse'
  , 'Inventory'
  , 'Inventory No.'
  , 'Inventory Web Image'
  , 'Item Desc'
  , 'Item Status'
  , 'ITEM VALUE'
  , 'Items'
  , 'Last Deal'
  , 'Last Deal No'
  , 'Last Order'
  , 'Last Order No'
  , 'Last Value'
  , 'Light Blue'
  , 'line items'
  , 'Liquid'
  , 'List'
  , 'Location:'
  , 'Login'
  , 'Logoff'
  , 'Manufacturer'
  , 'Matching Orders'
  , 'Messages'
  , 'Mode'
  , 'Move To Aisle/Shelf'
  , 'Move To Location'
  , 'Multi-Order'
  , 'New'
  , 'New Container'
  , 'New Order'
  , 'New Time Log Entry'
  , 'Next'
  , 'None'
  , 'Note'
  , 'Notes'
  , 'No'
  , 'OK'
  , 'On Set'
  , 'On PO'
  , 'On Order'
  , 'Options'
  , 'Out'
  , 'Out Value'
  , 'Ord'
  , 'Order'
  , 'Ordered'
  , 'Order Check-In'
  , 'Order Date'
  , 'Order Desc'
  , 'Order Desc.'
  , 'Order Item Status'
  , 'Order No'
  , 'Order Number'
  , 'Order Staging'
  , 'Overlay Color'
  , 'Override Availability Reservation'
  , 'Owner'
  , 'Package Truck'
  , 'Package Truck Menu'
  , 'Paper'
  , 'Parts'
  , 'Password'
  , 'Password is required'
  , 'Pending'
  , 'Pending Exchange'
  , 'Pending Items'
  , 'Period Total'
  , 'Photo'
  , 'Physical Inventory'
  , 'Physical Inventory No'
  , 'Photo Description'
  , 'Pictures'
  , 'Pick Date'
  , 'PO'
  , 'PO Desc.'
  , 'PO No'
  , 'PO No.'
  , 'PO Receive'
  , 'PO Return'
  , 'Preferences'
  , 'Previous'
  , 'Previous Quotes'
  , 'Privacy Policy'
  , 'Primary Vendor'
  , 'Production'
  , 'Project'
  , 'Project No'
  , 'Manufacturer'
  , 'PO No.'
  , 'PO Sub-Receive'
  , 'PO Sub-Return'
  , 'PO<br>Receive'
  , 'PO<br>Return'
  , 'Prospect'
  , 'Purchase Order'
  , 'QC'
  , 'QC Rq\'d'
  , 'Quik Check-In'
  , 'Qty'
  , 'Qty Ordered'
  , 'Quantity'
  , 'QuikIn'
  , 'QuikPick'
  , 'Quote'
  , 'Quote No'
  , 'Quote / Order No'
  , 'Rate'
  , 'Receive'
  , 'Receive by'
  , 'Receive Date'
  , 'Receive Inventory'
  , 'Reconcile'
  , 'Red'
  , 'Reef'
  , 'Return Inventory'
  , 'Receive PO'
  , 'Receive On Set'
  , 'Received'
  , 'Refresh'
  , 'Ref No Box'
  , 'Ref No Pallet'
  , 'Release'
  , 'Released'
  , 'Remain'
  , 'Remaining'
  , 'Remove Item'
  , 'Remove Item from Container?'
  , 'Rent'
  , 'RentalWorks'
  , 'Repair'
  , 'Repair (Complete)'
  , 'Repair (Release)'
  , 'Repair Menu'
  , 'Repair No'
  , 'Repair No. / BC'
  , 'Repair Order'
  , 'Replace'
  , 'Required'
  , 'Retire'
  , 'Retire from'
  , 'Retire from Order'
  , 'Retire from Warehouse'
  , 'Retire Items'
  , 'Retire Quantity'
  , 'Retire Reason'
  , 'Return'
  , 'Return by'
  , 'Return To Vendor'
  , 'Returned'
  , 'Responsible Person'
  , 'RFID'
  , 'RFID Check-In'
  , 'RFID Staging'
  , 'RFID Staging / Check-Out'
  , 'Rmn'
  , 'Rusted Metal'
  , 'Scan'
  , 'Scannable<br/>Item'
  , 'Scan Barcode'
  , 'Scan Mode'
  , 'Select Deal...'
  , 'Select Item to Check-In...'
  , 'Select Item to Stage...'
  , 'Select Order...'
  , 'Select PO...'
  , 'Select Package Truck'
  , 'Select Physical Inventory'
  , 'Select PO (Receive)'
  , 'Select PO (Return)'
  , 'Select Deal'
  , 'Select Order'
  , 'Select PO'
  , 'Select Session'
  , 'Select Transfer'
  , 'Serial No. Selection'
  , 'Select QuikPick Type'
  , 'Sell'
  , 'Serial No'
  , 'Session'
  , 'Session No'
  , 'Session In'
  , 'Set Character'
  , 'Set Container No'
  , 'Set Character Name'
  , 'Set Location'
  , 'Set No.'
  , 'Set Receive Date'
  , 'Settings'
  , 'Shelf'
  , 'Ship Date'
  , 'Signature'
  , 'Silver'
  , 'Single Order'
  , 'Stage'
  , 'Stage Consigned Item'
  , 'Staging'
  , 'Staged'
  , 'Staged/Out'
  , 'Start Date'
  , 'Status'
  , 'Status Date'
  , 'Still Out'
  , 'Sub'
  , 'Sub By'
  , 'Sub-Receive'
  , 'Sub-Rental'
  , 'Sub-Rental/Sale'
  , 'Sub-Return'
  , 'Sub-Sale'
  , 'Sub-Vendor'
  , 'Submit'
  , 'Substitute Complete'
  , 'Substitute Item'
  , 'Vendor/Consignor'
  , 'Summary'
  , 'Support'
  , 'Swap'
  , 'Take Picture'
  , 'Text Color'
  , 'Texture'
  , 'Time Log'
  , 'Tint'
  , 'To Truck'
  , 'To Warehouse'
  , 'Total'
  , 'Track Loss Amount'
  , 'Tracked By'
  , 'Transfer'
  , 'Transfer In'
  , 'Transfer In Menu'
  , 'Transfer No'
  , 'Transfer Order'
  , 'Transfer Out'
  , 'Transfer Repair'
  , 'Transparent'
  , 'Truck'
  , 'Truck No'
  , 'Truck No.'
  , 'Update'
  , 'User'
  , 'Unassigned Items'
  , 'Unstage'
  , 'Unstage Item?'
  , 'Update'
  , 'Utilities'
  , 'Vendor'
  , 'View Time Log Entries'
  , 'Warehouse'
  , 'Waterfall'
  , 'Web Image'
  , 'W/H'
  , 'White'
  , 'Would you like to add this to the order?'
  , 'Yes'
  , 'Yosemite'
];

RwLanguages.cultures.neutral = {};
for (var i = 0; i < RwLanguages.captions.length; i++) {
    RwLanguages.cultures.neutral[RwLanguages.captions[i]] = RwLanguages.captions[i];
}

RwLanguages.cultures.en = {

};

RwLanguages.cultures.enUs = {

};

RwLanguages.cultures.es = {
    'Barcode / Icode': 'Código Barras / I-Code'
  , 'Check-In': 'Facturar'
  , 'Check-In Menu': 'Facturar Menú'
  , 'Deal': 'Tratar'
  , 'Home': 'Casa'
  , 'Email': 'E-mail'
  , 'Exchange': 'Intercambio'
  , 'Inventory': 'Inventario'
  , 'Item Status': 'Estado Elemento'
  , 'Login': 'Iniciar Sesión'
  , 'Logoff': 'Cierre Sesión'
  , 'Multi-Order': 'Multi-Order'
  , 'Options': 'Opciones'
  , 'Order': 'Orden'
  , 'Package Truck': 'Paquete Camiones'
  , 'Physical Inventory': 'Physical Inventory'
  , 'Password': 'Password'
  , 'QC': 'QC'
  , 'Scan Barcode': 'Scan Barcode'
  , 'Repair': 'Repair'
  , 'Single Order': 'Single Order'
  , 'Session': 'Session'
  , 'Staging': 'Staging'
  , 'Sub-Receive': 'Sub-Receive'
  , 'Sub-Return': 'Sub-Return'
  , 'Transfer': 'Transfer'
  , 'Utilities': 'Utilities'
};

RwLanguages.cultures.en   = jQuery.extend({}, RwLanguages.cultures.neutral, RwLanguages.cultures.en);
RwLanguages.cultures.enUs = jQuery.extend({}, RwLanguages.cultures.en,      RwLanguages.cultures.enUs);
RwLanguages.cultures.es   = jQuery.extend({}, RwLanguages.cultures.neutral, RwLanguages.cultures.es);


RwLanguages.cultures.marvel = {
    //rename Item to Asset
    'Add Item': 'Add Asset',
    'Assign Items': 'Assign Assets',
    'Item Location': 'Asset Location',
    'Item Set Location': 'Asset Set Location',
    'Check In Item': 'Check In Asset',
    'Container<br/>Item': 'Container<br/>Asset',
    'Container Items': 'Container Assets',
    'Item Desc': 'Asset Desc',
    'Item Status' : 'Asset Status',
    'ITEM VALUE': 'ASSET VALUE',
    'Items': 'Assets',        
    'Pending Items': 'Pending Assets',
    'Remove Item': 'Remove Asset',
    'Remove Item from Container?': 'Remove Asset from Container?',
    'Retire Items': 'Retire Assets',
    'Select Item to Check-In...': 'Select Asset to Check-In...',
    'Select Item to Stage...': 'Select Asset to Stage...',
    'Stage Consigned Item': 'Stage Consigned Item',
    'Substitute Item': 'Substitute Asset',
    'Unassigned Items': 'Unassigned Assets',
    'Unstage Item?': 'Unstage Asset?',

    'Bar Code / I-Code': 'Barcode',
    'Deal':              'Production',
    'Deal Desc.':        'Production Desc.',
    'Deal No':           'Production No',
    'Deal No.':          'Production No.',
    'Order':             'Set',
    'Order Check-In':    'Set Check-In',
    'Order Desc.':       'Set Desc.',
    'Order Item Status': 'Set Character Status',
    'Order No':          'Set No',
    'Order Number':      'Set Number',
    'Order Staging':     'Set Staging'
    
};
RwLanguages.cultures.marvel = jQuery.extend({}, RwLanguages.cultures.enUs,      RwLanguages.cultures.marvel);

if ((!localStorage.getItem('currentCulture')) || (!RwLanguages.cultures.hasOwnProperty(localStorage.getItem('currentCulture')))) {
    localStorage.setItem('currentCulture', 'enUs');
    RwLanguages.currentCulture = localStorage.getItem('currentCulture');
}

//Eventually RwLanguages need to be replaced with AppLanguages
AppLanguages = RwLanguages;