declare var masterController: WebMaster;
declare var FwCharge: any;
declare var FwLanguages: any;
declare var FwMobileMasterController: any;
declare var FwSecurity: any;
declare var DayPilot: any;
declare var moment: any;
declare var Sortable: any;
declare var CKEDITOR: any;