-- I want to update this .NET code so the responsible person stuff is done in SQL.  
--I also want it to block creating contracts from other users suspended sessions
--public static dynamic WebCreateContract(DwSqlConnection conn, string usersId, string contractType,  string contractId,  string orderId, string responsiblePersonId)
--{
--    dynamic result;
--    DwSqlCommand sp, qryUpdateContract, qryContract;
            
--    sp = new DwSqlCommand(conn, "dbo.webcreatecontract");
--    sp.AddParameter("@contracttype", contractType);
--    sp.SetParameter("@contractid",   SqlDbType.NVarChar, ParameterDirection.InputOutput, contractId);
--    sp.AddParameter("@orderid",      orderId);
--    sp.AddParameter("@usersid",      usersId);
--    sp.AddParameter("@status",       SqlDbType.Int,      ParameterDirection.Output);
--    sp.AddParameter("@msg",          SqlDbType.NVarChar, ParameterDirection.Output);
--    sp.Execute();
--    result = new ExpandoObject();
--    result.contractId = sp.GetParameter("@contractid").ToString().TrimEnd();
--    result.status     = sp.GetParameter("@status").ToInt32();
--    result.msg        = sp.GetParameter("@msg").ToString().TrimEnd();
--    if ((result.status == 0) && (contractType == RwAppData.CONTRACT_TYPE_OUT) && (!string.IsNullOrEmpty(responsiblePersonId)) && (!string.IsNullOrEmpty(contractId)))
--    {
--        qryUpdateContract = new DwSqlCommand(conn);
--        qryUpdateContract.Add("update contract");
--        qryUpdateContract.Add("set responsiblepersonid = @responsiblePersonId");
--        qryUpdateContract.Add("where contractid        = @contractId");
--        qryUpdateContract.AddParameter("@responsiblePersonId", responsiblePersonId);
--        qryUpdateContract.AddParameter("@contractId", contractId);
--        qryUpdateContract.ExecuteNonQuery();
--    }
--    return result;
--}